# Generated by Django 4.1 on 2022-12-19 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=30, verbose_name="昵称")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatar", verbose_name="头像"
                    ),
                ),
                ("openid", models.CharField(max_length=30, verbose_name="openid")),
                (
                    "QQ",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="QQ"
                    ),
                ),
                (
                    "WeChat",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="WeChat"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "collection_num",
                    models.PositiveIntegerField(default=0, verbose_name="收藏数"),
                ),
                (
                    "UploadFile_num",
                    models.PositiveIntegerField(default=0, verbose_name="上传文件数"),
                ),
                (
                    "DownloadFile_num",
                    models.PositiveIntegerField(default=0, verbose_name="下载文件数"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Users.user",
                        verbose_name="对应用户id",
                    ),
                ),
            ],
        ),
    ]
