# Generated by Django 4.1 on 2022-12-19 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Users", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=75, verbose_name="文件名")),
                ("suffix", models.CharField(max_length=15, verbose_name="后缀名")),
                ("address", models.URLField(verbose_name="资源路径")),
                ("size", models.CharField(max_length=30, verbose_name="文件大小")),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="学院"
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="学科"
                    ),
                ),
                (
                    "readme",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="简介"
                    ),
                ),
                (
                    "download_num",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="下载量"
                    ),
                ),
                ("auth_name", models.CharField(max_length=30, verbose_name="上传者昵称")),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Users.user",
                        verbose_name="上传者id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DownloadFilePost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fileID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Files.file",
                        verbose_name="下载文件id",
                    ),
                ),
                (
                    "userID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Users.user",
                        verbose_name="用户id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CollectionPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fileID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Files.file",
                        verbose_name="收藏文件id",
                    ),
                ),
                (
                    "userID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Users.user",
                        verbose_name="用户id",
                    ),
                ),
            ],
        ),
    ]
