# Generated by Django 4.1 on 2022-12-19 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Files", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collectionpost",
            old_name="fileID",
            new_name="file",
        ),
        migrations.RenameField(
            model_name="collectionpost",
            old_name="userID",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="downloadfilepost",
            old_name="fileID",
            new_name="file",
        ),
        migrations.RenameField(
            model_name="downloadfilepost",
            old_name="userID",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="file",
            old_name="user_id",
            new_name="user",
        ),
    ]
